// 📂 app/layout.tsx (서버 컴포넌트)
import type { Metadata } from 'next';

import RootLayoutClient from '@/components/RootLayoutClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
